import type { ThemeConfig } from "antd";

export const FONT_SANS =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', '微软雅黑', 'Noto Sans SC', 'Alibaba PuHuiTi', sans-serif";

export const FONT_MONO = "'SF Mono', Consolas, 'Liberation Mono', Menlo, 'Courier New', monospace";

/** China Post Ant Design Enterprise tokens from corporation/DESIGN.md */
export const colors = {
  primary: "#0F6B3D",
  primaryHover: "#148A4E",
  primaryActive: "#083B21",
  primaryDark: "#0B4E2C",
  primaryLight: "#EAF6EE",
  primaryBorder: "#BCE2C9",
  onPrimary: "#FFFFFF",
  success: "#00B578",
  warning: "#FA8C16",
  error: "#F5222D",
  info: "#1677FF",
  gold: "#D48806",
  goldBg: "#FFF7E6",
  surface: "#FFFFFF",
  surfaceLayout: "#F4F6F8",
  surfaceContainer: "#FAFAFA",
  onSurface: "#1D2129",
  onSurfaceVariant: "#666F80",
  onSurfaceDisabled: "#9E9E9E",
  outline: "#E5E6EB",
  outlineVariant: "#F0F2F5",
  alertSuccessBg: "#F6FFED",
  alertWarningBg: "#FFFBE6",
  alertErrorBg: "#FFF2F0",
  tagBlueBg: "#E6F4FF",
} as const;

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorPrimaryHover: colors.primaryHover,
    colorPrimaryActive: colors.primaryActive,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    colorInfo: colors.info,
    colorLink: colors.info,
    colorText: colors.onSurface,
    colorTextSecondary: colors.onSurfaceVariant,
    colorTextTertiary: colors.onSurfaceDisabled,
    colorTextQuaternary: colors.onSurfaceDisabled,
    colorTextDisabled: colors.onSurfaceDisabled,
    colorBorder: colors.outline,
    colorBorderSecondary: colors.outlineVariant,
    colorSplit: colors.outline,
    colorBgLayout: colors.surfaceLayout,
    colorBgContainer: colors.surface,
    colorBgElevated: colors.surface,
    colorBgSpotlight: colors.surfaceContainer,
    borderRadius: 6,
    borderRadiusLG: 12,
    borderRadiusSM: 4,
    controlHeight: 32,
    controlHeightLG: 40,
    fontFamily: FONT_SANS,
    fontFamilyCode: FONT_MONO,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
    boxShadowSecondary: "0 4px 16px rgba(0, 0, 0, 0.12)",
    boxShadowTertiary: "0 6px 24px rgba(0, 0, 0, 0.16)",
  },
  components: {
    Button: {
      primaryShadow: "none",
      defaultBorderColor: colors.outline,
      defaultColor: colors.onSurface,
      defaultHoverBorderColor: colors.primaryHover,
      defaultHoverColor: colors.primaryHover,
      borderRadius: 6,
      controlHeight: 32,
      controlHeightLG: 40,
      fontWeight: 500,
    },
    Input: {
      activeBorderColor: colors.primary,
      hoverBorderColor: colors.primaryHover,
      activeShadow: "0 0 0 2px rgba(15, 107, 61, 0.2)",
    },
    Select: {
      activeBorderColor: colors.primary,
      hoverBorderColor: colors.primaryHover,
      optionSelectedBg: colors.primaryLight,
    },
    Table: {
      headerBg: colors.surfaceContainer,
      headerColor: colors.onSurfaceVariant,
      headerSplitColor: colors.outline,
      rowHoverBg: "rgba(234, 246, 238, 0.5)",
      borderColor: colors.outline,
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      cellPaddingBlockMD: 12,
      cellPaddingInlineMD: 16,
      fontSize: 14,
    },
    Menu: {
      itemSelectedBg: colors.primaryLight,
      itemSelectedColor: colors.primary,
      itemHoverBg: colors.primaryLight,
      itemActiveBg: colors.primaryLight,
      itemColor: colors.onSurface,
      itemBorderRadius: 6,
      iconSize: 16,
    },
    Modal: {
      borderRadiusLG: 12,
      titleFontSize: 18,
    },
    Tag: {
      borderRadiusSM: 999,
    },
    Checkbox: {
      colorPrimary: colors.primary,
    },
    Pagination: {
      itemActiveBg: colors.surface,
      itemActiveColorDisabled: colors.onSurfaceDisabled,
      itemSize: 32,
      itemSizeSM: 32,
      fontSize: 14,
    },
  },
};
